name: lua_in_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  lua_dardo:
    path: ../LuaDardo

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
